version: "3"

services:
    server:
        build: ./server
        command: ./server -p 5
        volumes:
            - ./data/server:/data
        ports:
            - "8080:8080"
    lehnurr:
        restart: unless-stopped
        build: 
            context: ./lehnurr
            dockerfile: .docker/Dockerfile
        environment:
            - KEY=lehnurr
            - URL=ws://server:8080/spe_ed
            - TIME_URL=http://server:8080/spe_ed_time
        depends_on:
            - server
    jumpstart:
        restart: unless-stopped
        build: ./jumpstart
        environment:
            - KEY=jumpstart
            - URL=ws://server:8080/spe_ed
            - TIME_URL=http://server:8080/spe_ed_time
        depends_on:
            - server
    brot:
        restart: unless-stopped
        build: ./brot
        command: ./client -guihostname 0.0.0.0
        volumes:
            - ./data/brot_log:/go/src/app/log
        environment:
            - KEY=brot
            - URL=ws://server:8080/spe_ed
            - TIME_URL=http://server:8080/spe_ed_time
        depends_on:
            - server
    speedos:
        restart: unless-stopped
        build: ./speedos
        environment:
            - KEY=speedos
            - URL=ws://server:8080/spe_ed
            - TIME_URL=http://server:8080spe_ed_time
        depends_on:
            - server
    chillow:
        restart: unless-stopped
        build: ./chillow
        environment:
            - KEY=chillow
            - URL=ws://server:8080/spe_ed
            - TIME_URL=http://server:8080/spe_ed_time
        depends_on:
            - server

